### ISSUE TITLE
Peer node connection in csc

### ISSUE THREAD

**Issue by blockchain-app12** [coinex-smart-chain/csc#3]
#### System information

Geth version: `1.0.1-stable`
OS & Version: Linux
Commit hash : (if `develop`)

#### Expected behaviour
Need to connect peer node

#### Actual behaviour
Trying to connect peer node but nodeInfo in csc always shows localhost connection.So can't able to connect with another server.

**Comment by liuzuowei** [comment]
Do you want to connect to the rpc api? You have to set the HTTP-RPC server listening interface with '--http.addr'.

**Comment by liuzuowei** [comment]
> #### System information
> Geth version: `1.0.1-stable` OS & Version: Linux Commit hash : (if `develop`)
> 
> #### Expected behaviour
> Need to connect peer node
> 
> #### Actual behaviour
> Trying to connect peer node but nodeInfo in csc always shows localhost connection.So can't able to connect with another server.

Do you want to connect to the rpc api? You have to set the HTTP-RPC server listening interface with '--http.addr'.

**Comment by blockchain-app12** [comment]
> > #### System information
> > Geth version: `1.0.1-stable` OS & Version: Linux Commit hash : (if `develop`)
> > #### Expected behaviour
> > Need to connect peer node
> > #### Actual behaviour
> > Trying to connect peer node but nodeInfo in csc always shows localhost connection.So can't able to connect with another server.
> 
> Do you want to connect to the rpc api? You have to set the HTTP-RPC server listening interface with '--http.addr'.

Hi @liuzuowei 
I have set HTTP-RPC but not working
 '--http.addr 0.0.0.0'

**Comment by cccCoding** [comment]
> > > #### System information
> > > Geth version: `1.0.1-stable` OS & Version: Linux Commit hash : (if `develop`)
> > > #### Expected behaviour
> > > Need to connect peer node
> > > #### Actual behaviour
> > > Trying to connect peer node but nodeInfo in csc always shows localhost connection.So can't able to connect with another server.
> > 
> > 
> > Do you want to connect to the rpc api? You have to set the HTTP-RPC server listening interface with '--http.addr'.
> 
> Hi @liuzuowei I have set HTTP-RPC but not working '--http.addr 0.0.0.0'

Can you paste your start command and log here?  And use `netstat` commond to show the netword stats.

**Comment by blockchain-app12** [comment]
> > > > #### System information
> > > > Geth version: `1.0.1-stable` OS & Version: Linux Commit hash : (if `develop`)
> > > > #### Expected behaviour
> > > > Need to connect peer node
> > > > #### Actual behaviour
> > > > Trying to connect peer node but nodeInfo in csc always shows localhost connection.So can't able to connect with another server.
> > > 
> > > 
> > > Do you want to connect to the rpc api? You have to set the HTTP-RPC server listening interface with '--http.addr'.
> > 
> > 
> > Hi @liuzuowei I have set HTTP-RPC but not working '--http.addr 0.0.0.0'
> 
> Can you paste your start command and log here? And use `netstat` commond to show the netword stats.

./cetd --datadir data init ../genesis.json

./cetd --datadir data --nodiscover --networkid 200 --port 30304 -http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*"  --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock console
![Screenshot from 2022-01-11 12-19-59](https://user-images.githubusercontent.com/48212011/148951203-0cea38c8-5187-4ac1-a9a4-a7a263db9970.png)


I have attached a screenshot of server ip enode, but it shows localhost

**Comment by cccCoding** [comment]
> > > > > #### System information
> > > > > Geth version: `1.0.1-stable` OS & Version: Linux Commit hash : (if `develop`)
> > > > > #### Expected behaviour
> > > > > Need to connect peer node
> > > > > #### Actual behaviour
> > > > > Trying to connect peer node but nodeInfo in csc always shows localhost connection.So can't able to connect with another server.
> > > > 
> > > > 
> > > > Do you want to connect to the rpc api? You have to set the HTTP-RPC server listening interface with '--http.addr'.
> > > 
> > > 
> > > Hi @liuzuowei I have set HTTP-RPC but not working '--http.addr 0.0.0.0'
> > 
> > 
> > Can you paste your start command and log here? And use `netstat` commond to show the netword stats.
> 
> ./cetd --datadir data init ../genesis.json
> 
> ./cetd --datadir data --nodiscover --networkid 200 --port 30304 -http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock console ![Screenshot from 2022-01-11 12-19-59](https://user-images.githubusercontent.com/48212011/148951203-0cea38c8-5187-4ac1-a9a4-a7a263db9970.png)
> 
> I have attached a screenshot of server ip enode, but it shows localhost

If you want to connect to other nodes, you can't specify a network id of 200. 

So If you want to connect to the CSC mainnet, the start command should be 
```
./cetd --datadir data --nodiscover --port 30304 -http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock console
```

if you want to connect to the testnet, the start command should be 
```
./cetd --datadir data --nodiscover --testnet --port 30304 -http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock console
```

**Comment by blockchain-app12** [comment]
> > > > > > #### System information
> > > > > > Geth version: `1.0.1-stable` OS & Version: Linux Commit hash : (if `develop`)
> > > > > > #### Expected behaviour
> > > > > > Need to connect peer node
> > > > > > #### Actual behaviour
> > > > > > Trying to connect peer node but nodeInfo in csc always shows localhost connection.So can't able to connect with another server.
> > > > > 
> > > > > 
> > > > > Do you want to connect to the rpc api? You have to set the HTTP-RPC server listening interface with '--http.addr'.
> > > > 
> > > > 
> > > > Hi @liuzuowei I have set HTTP-RPC but not working '--http.addr 0.0.0.0'
> > > 
> > > 
> > > Can you paste your start command and log here? And use `netstat` commond to show the netword stats.
> > 
> > 
> > ./cetd --datadir data init ../genesis.json
> > ./cetd --datadir data --nodiscover --networkid 200 --port 30304 -http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock console ![Screenshot from 2022-01-11 12-19-59](https://user-images.githubusercontent.com/48212011/148951203-0cea38c8-5187-4ac1-a9a4-a7a263db9970.png)
> > I have attached a screenshot of server ip enode, but it shows localhost
> 
> If you want to connect to other nodes, you can't specify a network id of 200.
> 
> So If you want to connect to the CSC mainnet, the start command should be
> 
> ```
> ./cetd --datadir data --nodiscover --port 30304 -http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock console
> ```
> 
> if you want to connect to the testnet, the start command should be
> 
> ```
> ./cetd --datadir data --nodiscover --testnet --port 30304 -http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock console
> ```

Hi,
 Running private network.

**Comment by cccCoding** [comment]
> > > > > > > #### System information
> > > > > > > Geth version: `1.0.1-stable` OS & Version: Linux Commit hash : (if `develop`)
> > > > > > > #### Expected behaviour
> > > > > > > Need to connect peer node
> > > > > > > #### Actual behaviour
> > > > > > > Trying to connect peer node but nodeInfo in csc always shows localhost connection.So can't able to connect with another server.
> > > > > > 
> > > > > > 
> > > > > > Do you want to connect to the rpc api? You have to set the HTTP-RPC server listening interface with '--http.addr'.
> > > > > 
> > > > > 
> > > > > Hi @liuzuowei I have set HTTP-RPC but not working '--http.addr 0.0.0.0'
> > > > 
> > > > 
> > > > Can you paste your start command and log here? And use `netstat` commond to show the netword stats.
> > > 
> > > 
> > > ./cetd --datadir data init ../genesis.json
> > > ./cetd --datadir data --nodiscover --networkid 200 --port 30304 -http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock console ![Screenshot from 2022-01-11 12-19-59](https://user-images.githubusercontent.com/48212011/148951203-0cea38c8-5187-4ac1-a9a4-a7a263db9970.png)
> > > I have attached a screenshot of server ip enode, but it shows localhost
> > 
> > 
> > If you want to connect to other nodes, you can't specify a network id of 200.
> > So If you want to connect to the CSC mainnet, the start command should be
> > ```
> > ./cetd --datadir data --nodiscover --port 30304 -http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock console
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if you want to connect to the testnet, the start command should be
> > ```
> > ./cetd --datadir data --nodiscover --testnet --port 30304 -http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth, net, web3, personal, miner, admin, debug" --allow-insecure-unlock console
> > ```
> 
> Hi, Running private network.

OK, I see. 
Have you performed the following steps：

* Initialize validator configuration: extraData Modify the initial validator address by replacing 42eacf5b37540920914589a6b1b5e45d82d0c1ca with user's own validator address. For multiple initial validator nodes, simply concatenate the addresses and replace them.

* Initial addresses:

0x0000000000000000000000000000000000001000：validator contract address
0x0000000000000000000000000000000000001001：slash contract address
0x96b4ded06d3447030f82d4722c641171566574df：Pre-allocate a certain number of original token addresses. The number of token and addresses for pre-allocation can be set according to user needs.

The link to the documentation is [here](https://docs.coinex.org/#/en-us/node_private_chain)
