### ISSUE TITLE
Run a node on testnet

### ISSUE THREAD

**Issue by mostafabarmshory** [coinex-smart-chain/csc#4]
I`m looking for a document that shows how to launch a node. I follow the command (from the official site). but faced with the following error:

```
INFO [07-05|08:58:39.747] Looking for peers                        peercount=0 tried=3 static=3
INFO [07-05|08:59:14.747] Looking for peers                        peercount=0 tried=3 static=3
INFO [07-05|08:59:49.747] Looking for peers                        peercount=0 tried=3 static=3
INFO [07-05|09:00:24.748] Looking for peers                        peercount=0 tried=3 static=3
INFO [07-05|09:00:59.749] Looking for peers                        peercount=0 tried=3 static=3
INFO [07-05|09:01:34.750] Looking for peers                        peercount=0 tried=3 static=3
```

It seems the peer node is not accessible. How to fix this? is there any online peer node list? Is it possible to set peer node manually?

**Comment by liuzuowei** [comment]
The testnet peer nodes are normal.

**Comment by liuzuowei** [comment]
> The testnet peer nodes are normal. Can you share your operated step

**Comment by liuzuowei** [comment]
> I`m looking for a document that shows how to launch a node. I follow the command (from the official site). but faced with the following error:
> 
> ```
> INFO [07-05|08:58:39.747] Looking for peers                        peercount=0 tried=3 static=3
> INFO [07-05|08:59:14.747] Looking for peers                        peercount=0 tried=3 static=3
> INFO [07-05|08:59:49.747] Looking for peers                        peercount=0 tried=3 static=3
> INFO [07-05|09:00:24.748] Looking for peers                        peercount=0 tried=3 static=3
> INFO [07-05|09:00:59.749] Looking for peers                        peercount=0 tried=3 static=3
> INFO [07-05|09:01:34.750] Looking for peers                        peercount=0 tried=3 static=3
> ```
> 
> It seems the peer node is not accessible. How to fix this? is there any online peer node list? Is it possible to set peer node manually?

Can you share your operated steps?

**Comment by mostafabarmshory** [comment]
Tx to your reply @liuzuowei 

First of all, I init a node with the following command:

    cetd --datadir /home/maso/cetd init

Then I try to run the node with the following command:

    cetd --datadir /home/maso/cetd --syncmod fast 

This is what I did. But it did not succeed to find a peer. I`m wonder if there is a way to define bootnodes manually. But I cant find a list of peer nodes.

**Comment by liuzuowei** [comment]
> Tx to your reply @liuzuowei
> 
> First of all, I init a node with the following command:
> 
> ```
> cetd --datadir /home/maso/cetd init
> ```
> 
> Then I try to run the node with the following command:
> 
> ```
> cetd --datadir /home/maso/cetd --syncmod fast 
> ```
> 
> This is what I did. But it did not succeed to find a peer. I`m wonder if there is a way to define bootnodes manually. But I cant find a list of peer nodes.

Your operations are right and you may have to check your network is normal. I tried in local and it's normal. And if you want to run a testnet node, you also have to set the --testnet option，and you run a mainnet node without the --testnet option .

**Comment by mostafabarmshory** [comment]
Dear @liuzuowei
How the CETD finds a peer node? I want to debug and find the problem. 

I think the CETD start with a pre-defined node IP address. If so, what is the node IP.

**Comment by liuzuowei** [comment]
> You can find the nodes's ip in the website
https://docs.coinex.org/#/testnet
