### ISSUE TITLE
Block sealing failed err="unauthorized signer" while running a validator

### ISSUE THREAD

**Issue by mostafabarmshory** [coinex-smart-chain/csc#7]
I am trying to run a validator. I've generated an account and transferred CET. after successfully setting it up on Linux (it is initialized on the main network) whenever trying to start mine, the following error appears:

```
INFO [09-06|18:20:16.203|miner/worker.go:999]               Commit new mining work                   number=12627591 sealhash="815876…36a6b8" uncles=2 txs=0  gas=0       fees=0           elapsed=3.172ms
WARN [09-06|18:20:16.204|miner/worker.go:567]               Block sealing failed                     err="unauthorized validator"
```

How can I fix it?

**Comment by liuzuowei** [comment]
> I am trying to run a validator. I've generated an account and transferred CET. after successfully setting it up on Linux (it is initialized on the main network) whenever trying to start mine, the following error appears:
> 
> ```
> INFO [09-06|18:20:16.203|miner/worker.go:999]               Commit new mining work                   number=12627591 sealhash="815876…36a6b8" uncles=2 txs=0  gas=0       fees=0           elapsed=3.172ms
> WARN [09-06|18:20:16.204|miner/worker.go:567]               Block sealing failed                     err="unauthorized validator"
> ```
> 
> How can I fix it?

it seems you want to be a validator, you have to staking cet at least 10000.
